// Import createSlice from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Create a slice for authentication
const authSlice = createSlice({
  name: "auth", // Name of the slice
  initialState: { user: null, token: null }, // Initial state
  reducers: {
    // Reducer for logging in a user
    login(state, action) {
      state.user = action.payload.user;
      state.token = action.payload.token;
    },
    // Reducer for logging out a user
    logout(state) {
      state.user = null;
      state.token = null;
    },
  },
});

// Export the actions generated by the slice
export const { login, logout } = authSlice.actions;

// Export the reducer to be used in the store configuration
export default authSlice.reducer;
